name: Haskell CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Bazel
    runs-on: ubuntu-latest
    strategy:

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/cache@v1
      id: cache-cabal
      name: Cache Bazel artifacts
      with:
        path: .bazel-cache
        key: ${{ runner.os }}-bazel-${{ hashFiles('semantic-*/**/*.hs') }}-${{ hashFiles('**/BUILD.bazel') }}
        restore-keys: |
          ${{ runner.os }}-bazel-

    - name: Build & test
      run: |
        bazel build //...
        bazel test //...
